### ISSUE TITLE
Cannot reproduce the paper result

### ISSUE THREAD

**Issue by fake-warrior8** [sunoh-kim/pps#3]
Hi, I reproduce the results using the CPL features, your code and environments. The results are as follows

Charades 
R1 IoU=0.3, 0.5, 0.7 R5 IoU=0.3 0.5 0.7
69.06 **51.49** **26.16** 99.18 86.23 53.01 (paper)
68.75 50.32 24.89 98.54 87.49 52.94 (your_hyper)
67.80 50.13 25.59 98.48 85.85 51.74 (your_hyper_refact)

Anet
R1 IoU=0.1, 0.3, 0.5 R5 IoU=0.1, 0.3, 0.5
81.84 **59.29** 31.25 **95.28** **85.54** **71.32** (paper)
79.65 52.58 29.12 91.40 71.70 54.27 (your_hyper)
81.57 57.26 31.21 91.97 74.89 58.25 (your_hyper_refact)

1. I select the best test result using R1 mIoU, which is the same as CPL. I found mIoU's results are positively correlated  with  these above indicators.
2. I used A100 but not 4090.

**Comment by sunoh-kim** [comment]
The best mIoN does not necessarily give the best results. Because the mIoN is average, it can be highly responsive to outliers. Since we have three R1 metrics and three R5 metrics, it would be good to see what results these metrics show. So, please use wandb or tensorboard to see the results. The graph below is the learning curve from the wandb in my environment.

<img width="944" alt="CharadesSTA_Results_R1" src="https://github.com/user-attachments/assets/1998965d-1fea-490d-9e6a-da65b14ed7de">
<img width="947" alt="CharadesSTA_Results_R5" src="https://github.com/user-attachments/assets/522b8e46-9764-4aa1-abb1-829e41eb5df0">

<img width="842" alt="ActivityNetCaptions_Results_R1" src="https://github.com/user-attachments/assets/fdf9fc63-3e3f-4568-8824-14fb0b1675ef">
<img width="838" alt="ActivityNetCaptions_Results_R5" src="https://github.com/user-attachments/assets/22d8822f-b0a6-4606-ae4c-141b50745d2f">
